myname = input()
print("Hi!!! " + myname)
print(len(myname))
check = int(-3.14)
check1 = str(45)
check2 = float(5)
print(type(check))
print(type(check1))
print(type(check2))
print(type(myname))
check5 = int(7.7)
print(check5)
check6 = 45<45
print(check6)